Repository Team-walkies/Walkie-server, pull requests merged in 2025-04, with the labels that each got.

#116 Hotfix/#115 : swagger가 띄워진 `"https://truthguard.site"` 주소를 CORS 허용 설정에 추가
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
Labels: fix, 🔴 긴급

#120 fix/#117 : egg 정보의 캐릭터 디테일 정보 추가
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/GetEggDetailResponse.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/GetEggResponse.java
Labels: fix, 🟡 보통

#122 Hotfix/#121 : 토큰 시간 만료 시, 500이 아닌 401 Status를 보내도록 수정
  src/main/java/site/walkies/walkie/domain/spot/entity/SpotPhoto.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
Labels: fix, 🔴 긴급

#128 Feat/#126 : 멤버 로그아웃 API 구현
  src/main/java/site/walkies/walkie/domain/auth/controller/AuthController.java
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
Labels: feat, 🟠 높음

#130 Feat/#129 : 멤버의 기록한 스팟 개수 리턴 API 구현
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: feat, 🟠 높음

#132 Fix/#127 : 멤버의 알이 없을 때, null을 넣는 객체를 보내도록 변경
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🔴 긴급

#134 Fix/#133 : 회원가입 시, 기본 캐릭터 생성 로직 수정
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
Labels: fix, 🟠 높음

#139 Fix/#135: 유저 캐릭터 틀 추가
  src/main/java/site/walkies/walkie/domain/character/controller/UserCharacterController.java
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
Labels: fix, 🟡 보통

#141 Fix/#138 : SWAGGER 파라미터 명시
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
Labels: fix, 🟡 보통

#140 Fix/#136: 알, 리뷰, 캐릭터 삭제 구현
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
Labels: feat, 🟡 보통

#145 fix/#144 : lat, lon의 default 값을 추가함으로서 null 에러 해결
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/request/PostStepRequest.java
Labels: fix, 🟡 보통

#147 fix/#146 : 리뷰 수정 및 삭제 유저 검증 로직 추가
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: fix, 🟡 보통

#149 fix/$148:json 형식 추가
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewResponse.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/PatchReviewResponse.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/PostReviewResponse.java
Labels: fix, 🟡 보통

#153 fix/#152:delete cd 확인 및 member 부적절 검색 제거
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
Labels: fix, 🟡 보통

#154 Fix/#151 : 유저 주변 스팟 조회 시, 방문 여부에 따라 응답 달라지도록 수정
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/spot/controller/SpotController.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
Labels: fix, 🟠 높음

#156 Refactor/#155 : Spot 카테고리 마이그레이션 및 데이터 변환 작업
  src/main/java/site/walkies/walkie/domain/spot/entity/Spot.java
  src/main/java/site/walkies/walkie/domain/spot/enums/SpotKeyword.java
  src/main/java/site/walkies/walkie/domain/spot/enums/SpotType.java
  src/main/java/site/walkies/walkie/domain/spot/migration/SpotKeywordMigrationRunner.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
Labels: refactor, 🟠 높음

#158 Fix/#157 : 회원가입 시 중복된 계정을 등록하려고 할 때 예외처리 로직 추가
  src/main/java/site/walkies/walkie/domain/member/repository/MemberRepository.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: fix, 🔴 긴급
