Repository Team-walkies/Walkie-server, pull requests merged in 2025-05, with the labels that each got.

#160 Fix/#159-리뷰 조회시 spot type 전달
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewResponse.java
Labels: fix, 🟡 보통

#162 fix:.#161 EggResponse 캐릭터 타입, 랭크, 클래스 정보 추가
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/EggResponse.java
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🟡 보통

#167 feat/#163: 알 생성 api 구현
  src/main/java/site/walkies/walkie/domain/egg/controller/EggController.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/request/CreateEggRequest.java
Labels: feat, 🟠 높음

#168 Fix/#164: LocalDate 배열로 json을 보내는 부분 format 지정
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/ObtainedDetail.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/EggResponse.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/GetEggDetailResponse.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/GetEggResponse.java
  src/main/java/site/walkies/walkie/domain/notice/service/dto/response/NoticeResponse.java
Labels: fix, 🟡 보통

#169 Feat/#165 : 회원 가입 웹훅 기능 개발
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/global/web/exception/GlobalExceptionHandler.java
  src/main/java/site/walkies/walkie/global/webhook/DiscordNotifier.java
Labels: feat, 🟡 보통

#172 Feat/#171 : JWT토큰 만료시간 운영 환경 기준으로 변경
  src/main/java/site/walkies/walkie/global/auth/utils/JWTProvider.java
  src/main/resources/application.properties
Labels: feat, 🔴 긴급

#174 Fix/#173 : 레벨업 중인 알이 null일 경우 NPE 발생하는 문제 수정
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🔴 긴급

#176 Fix/#175 : 리뷰 작성 시 탐험&기록 수 오르지 않던 문제 수정
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
Labels: fix, 🔴 긴급

#180 Fix/#179: 리뷰 삭제시 member의 컬럼값 감소
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
Labels: fix, 🟡 보통

#181 Fix/#178 : 재탐험 기준에 따른 spot type(_VISITED) 표시 오류 수정
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
Labels: fix, 🔴 긴급

#183 Fix /#182: 캐릭터 회득 확률 조정
  src/main/java/site/walkies/walkie/global/probability/EggsProbability.java
Labels: fix, 🟡 보통

#185 Fix/#184 : 탈퇴한 유저가 토큰이 필요없는 API에 접근할 때 예외처리 로직 수정 + 리뷰 조회 시 날짜가 아닌 id를 기준으로 정렬하도록 수정
  src/main/java/site/walkies/walkie/domain/member/repository/MemberRepository.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
Labels: fix, 🔴 긴급

#190 Feat/#189: egg test를 위한 test api 구현
  src/main/java/site/walkies/walkie/domain/egg/entity/Egg.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/internal/controller/InternalController.java
Labels: feat, 🟡 보통
