Repository Team-walkies/Walkie-server, pull requests merged in 2025-06, with the labels that each got.

#197 Feat/#196 : 사용자 행동 추적 및 에러 진단을 위한 로그 추가
  src/main/java/site/walkies/walkie/WalkieApplication.java
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
  src/main/java/site/walkies/walkie/global/config/WebmvcConfig.java
  src/main/java/site/walkies/walkie/global/logging/RequestLoggingInterceptor.java
Labels: feat, 🟡 보통

#199 Fix/#198: 회원가입 시 생성된 Egg가 Member의 levelingEgg 필드에 반영되지 않는 문제를 해결하기 위한 트랜잭션 처리 개선
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
Labels: feat, 🟠 높음

#201 Refactor/#200 : 전략 패턴 적용하여 소셜 로그인 분기 로직 구조 개선
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
  src/main/java/site/walkies/walkie/domain/auth/strategy/AppleLoginStrategy.java
  src/main/java/site/walkies/walkie/domain/auth/strategy/KakaoLoginStrategy.java
  src/main/java/site/walkies/walkie/domain/auth/strategy/SocialLoginStrategy.java
Labels: refactor, 🟡 보통

#203 Fix/#202: 캐릭터 상세조회 사진 및 설명 추가 전달
  files/DEER_DINO.png
  files/DINO.png
  files/DRAGON_DINO.png
  files/GREEN_DINO.png
  files/GREEN_JELLYFISH.png
  files/JELLYFISH.png
  files/LIGHTNING_JELLYFISH.png
  files/MELONSODA_DINO.png
  files/NESSIE_DINO.png
  files/PANCAKE_DINO.png
  files/PINK_DINO.png
  files/PINK_JELLYFISH.png
  files/PURPLE_DINO.png
  files/PURPLE_JELLYFISH.png
  files/RABBIT_JELLYFISH.png
  files/RED_DINO.png
  files/RED_JELLYFISH.png
  files/SPACE_JELLYFISH.png
  files/STARFISH_JELLYFISH.png
  files/STRAWBERRY_JELLYFISH.png
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/GetCharacterDetailResponse.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
  src/main/java/site/walkies/walkie/global/file/FileController.java
  src/main/java/site/walkies/walkie/global/probability/CharacterProbability.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: fix, 🟡 보통

#208 Fix/#204 : 민트 다이노 오타 해결
  src/main/java/site/walkies/walkie/global/probability/CharacterProbability.java
Labels: fix, 🟡 보통

#210 Fix/#205: 파일 접근 경로 변경 및 파일 static 위치 변경
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/static/file/5f16ff3c-faae-4cd1-be90-29da46296d7720250303_135348.png
  src/main/resources/static/file/DEER_DINO.png
  src/main/resources/static/file/DINO.png
  src/main/resources/static/file/DRAGON_DINO.png
  src/main/resources/static/file/GREEN_DINO.png
  src/main/resources/static/file/GREEN_JELLYFISH.png
  src/main/resources/static/file/JELLYFISH.png
  src/main/resources/static/file/LIGHTNING_JELLYFISH.png
  src/main/resources/static/file/MELONSODA_DINO.png
  src/main/resources/static/file/NESSIE_DINO.png
  src/main/resources/static/file/PANCAKE_DINO.png
  src/main/resources/static/file/PINK_DINO.png
  src/main/resources/static/file/PINK_JELLYFISH.png
  src/main/resources/static/file/PURPLE_DINO.png
  src/main/resources/static/file/PURPLE_JELLYFISH.png
  src/main/resources/static/file/RABBIT_JELLYFISH.png
  src/main/resources/static/file/RED_DINO.png
  src/main/resources/static/file/RED_JELLYFISH.png
  src/main/resources/static/file/SPACE_JELLYFISH.png
  src/main/resources/static/file/STARFISH_JELLYFISH.png
  src/main/resources/static/file/STRAWBERRY_JELLYFISH.png
Labels: fix, 🟡 보통
