Repository Team-walkies/Walkie-server, pull requests merged in 2025-03, with the labels that each got.

#24 Fix/#23 멤버 entity에 탐험한 스팟, 프로필 공개 여부, 멤버 티어 추가
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
Labels: fix, 🔴 긴급

#25 Feat/#7- 알의 걸은 걸음수 업데이트 API 구현 완료
  src/main/java/site/walkies/walkie/domain/character/entity/UserCharacterBorn.java
  src/main/java/site/walkies/walkie/domain/character/repository/UserCharacterRepository.java
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/egg/controller/EggController.java
  src/main/java/site/walkies/walkie/domain/egg/entity/Egg.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/request/PostStepRequest.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: feat, 🟡 보통

#29 Feat/#26-보유한 캐릭터 리스트 조회 API 개발
  src/main/java/site/walkies/walkie/domain/character/controller/UserCharacterController.java
  src/main/java/site/walkies/walkie/domain/character/repository/UserCharacterBornRepository.java
  src/main/java/site/walkies/walkie/domain/character/repository/UserCharacterRepository.java
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/CharacterListResponse.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/GetCharacterResponse.java
Labels: feat, 🟡 보통

#31 Fix/#30- eggsListResponse Dto 추가
  src/main/java/site/walkies/walkie/domain/egg/controller/EggController.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/EggListResponse.java
Labels: fix

#35 Feat/#27-캐릭터 획득 정보 상세 조회 API 구현
  src/main/java/site/walkies/walkie/domain/character/controller/UserCharacterController.java
  src/main/java/site/walkies/walkie/domain/character/repository/UserCharacterBornRepository.java
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/GetCharacterDetailResponse.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/ObtainedDetail.java
Labels: feat, 🟡 보통

#38 Feat/#37 - 리뷰 작성 API 구현
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/entity/Review.java
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/request/ReviewData.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/PostReviewResponse.java
  src/main/java/site/walkies/walkie/domain/spot/entity/Spot.java
  src/main/java/site/walkies/walkie/domain/spot/repository/SpotRepository.java
  src/main/java/site/walkies/walkie/global/file/FileController.java
  src/main/java/site/walkies/walkie/global/file/FileService.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: feat, 🟠 높음

#41 Feat/#39-캘린더 리뷰 리스트 조회 API 구현
  files/5f16ff3c-faae-4cd1-be90-29da46296d7720250303_135348.png
  src/main/java/site/walkies/walkie/domain/character/controller/UserCharacterController.java
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewResponse.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/ReviewListResponse.java
Labels: feat, 🟡 보통

#45 Feat/#43- 리뷰 수정 API
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/request/PatchReviewRequest.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/PatchReviewResponse.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: feat, 🟡 보통

#47 Feat/#42-스팟 별 리뷰수 조회 API
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewCountResponse.java
Labels: feat, 🟡 보통

#48 feat/#44 - 리뷰 삭제 API 구현
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
Labels: feat, 🟡 보통

#52 Feat/#49-공지사항 등록 API 구현
  src/main/java/site/walkies/walkie/domain/notice/controller/NoticeController.java
  src/main/java/site/walkies/walkie/domain/notice/entity/Notice.java
  src/main/java/site/walkies/walkie/domain/notice/repository/NoticeRepository.java
  src/main/java/site/walkies/walkie/domain/notice/service/NoticeService.java
  src/main/java/site/walkies/walkie/domain/notice/service/dto/request/PostNoticeRequest.java
  src/main/java/site/walkies/walkie/domain/notice/service/dto/response/PostNoticeResponse.java
Labels: feat, 🟡 보통

#53 fix/#51 - egg 걸음수 업데이트시 객체 리턴하도록 변경
  src/main/java/site/walkies/walkie/domain/egg/controller/EggController.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/EggResponse.java
Labels: fix, 🟡 보통

#56 feat/#55-swagger 추가
  build.gradle
Labels: feat, 🟡 보통

#57 Feat/#32 : 카카오 로그인 구현(회원 저장)
  build.gradle
  src/main/java/site/walkies/walkie/domain/auth/controller/AuthController.java
  src/main/java/site/walkies/walkie/domain/auth/service/AppleService.java
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
  src/main/java/site/walkies/walkie/domain/auth/service/KakaoService.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/request/LoginRequestDto.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/response/KakaoTokenResponseDto.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/member/repository/MemberRepository.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/domain/member/service/dto/response/MemberResponseDto.java
  src/main/java/site/walkies/walkie/global/config/WebClientConfig.java
  src/main/resources/application.properties
Labels: feat, 🟠 높음

#59 Feat/#58- 디폴트 캐릭터 함수 구현
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/global/Tmap/TmapAPIService.java
Labels: feat, 🟡 보통

#62 fix/#66 - egg 리스트 획득 위치 및 날짜 정보 추가
  src/main/java/site/walkies/walkie/domain/egg/service/EggService.java
  src/main/java/site/walkies/walkie/domain/egg/service/dto/response/GetEggResponse.java
Labels: fix, 🟡 보통

#65 feat/#64: 공통 응답 처리 시 모든 요청에 대하여 응답을 보내도록 추가
  src/main/java/site/walkies/walkie/global/web/dto/response/SuccessResponse.java
Labels: feat, 🟠 높음

#67 Feat/#66-Auth 추가에 따른 추가 작업
  src/main/java/site/walkies/walkie/domain/character/controller/UserCharacterController.java
  src/main/java/site/walkies/walkie/domain/egg/controller/EggController.java
  src/main/java/site/walkies/walkie/domain/review/controller/ReviewController.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/config/OpenApiConfig.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
  src/main/java/site/walkies/walkie/global/config/WebmvcConfig.java
Labels: feat, 🔴 긴급

#74 Feat/#33 : 회원 정보 조회하기 API 개발
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: feat, 🟠 높음

#75 Feat/#73 : 멤버 정보 수정 API 개발
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
  src/main/java/site/walkies/walkie/domain/member/service/dto/request/MemberUpdateRequestDto.java
Labels: feat, 🟠 높음

#77 Fix/#70-캐릭터 종류 정보 추가
  src/main/java/site/walkies/walkie/domain/character/service/CharacterService.java
  src/main/java/site/walkies/walkie/domain/character/service/dto/response/GetCharacterDetailResponse.java
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewResponse.java
Labels: fix, 🟡 보통

#79 Fix/#78 : 토큰 유효시간 수정
  src/main/java/site/walkies/walkie/global/auth/utils/JWTProvider.java
Labels: fix, 🔴 긴급

#80 Feat/#76 : 멤버가 레벨업 시키는 알 변경
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
  src/main/java/site/walkies/walkie/domain/member/service/dto/request/MemberUpdateLevelingEggRequestDto.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: feat, 🟠 높음

#82 Feat/#81 : 멤버가 함께 걷는 캐릭터 변경
  src/main/java/site/walkies/walkie/domain/character/entity/UserCharacter.java
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
  src/main/java/site/walkies/walkie/domain/member/service/dto/request/MemberUpdateCharacterRequestDto.java
Labels: feat, 🟠 높음

#88 Fix/#87 : 멤버가 부화시키는 알 변경 시 알 picked 필드도 함께 변경되도록 수정
  src/main/java/site/walkies/walkie/domain/egg/entity/Egg.java
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🔴 긴급

#86 Feat/#83 : 멤버가 같이 걷는 캐릭터 조회
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: feat, 🟠 높음

#89 Feat/#84 : 멤버가 부화시키는 알 조회
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: feat, 🟠 높음

#90 Feat/#85 : 멤버 프로필 공개 여부 토글 기능
  src/main/java/site/walkies/walkie/domain/member/controller/MemberController.java
  src/main/java/site/walkies/walkie/domain/member/entity/Member.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: feat, 🟠 높음

#92 Fix/#91: memberService 오류 해결
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🔴 긴급

#94 Fix/#93 : egg의 response dto에 memberId도 함께 받아서 처리하도록 수정
  src/main/java/site/walkies/walkie/domain/member/service/MemberService.java
Labels: fix, 🔴 긴급

#101 Feat/#99
  src/main/java/site/walkies/walkie/domain/review/repository/ReviewRepository.java
  src/main/java/site/walkies/walkie/domain/spot/controller/SpotController.java
  src/main/java/site/walkies/walkie/domain/spot/entity/Spot.java
  src/main/java/site/walkies/walkie/domain/spot/entity/SpotPhoto.java
  src/main/java/site/walkies/walkie/domain/spot/enums/SpotType.java
  src/main/java/site/walkies/walkie/domain/spot/repository/SpotPhotoRepository.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
  src/main/java/site/walkies/walkie/domain/spot/service/dto/response/SpotResponseDto.java
  src/main/resources/application.properties
Labels: feat, 🟠 높음

#102 Feat/#100 : 유저 현 위치 기반 주변 스팟 조회하기
  build.gradle
  src/main/java/site/walkies/walkie/domain/spot/controller/SpotController.java
  src/main/java/site/walkies/walkie/domain/spot/entity/Spot.java
  src/main/java/site/walkies/walkie/domain/spot/repository/SpotRepository.java
  src/main/java/site/walkies/walkie/domain/spot/service/SpotService.java
  src/main/java/site/walkies/walkie/domain/spot/service/dto/request/SpotNearbyRequestDto.java
  src/main/java/site/walkies/walkie/domain/spot/service/dto/response/SpotNearbyResponseDto.java
  src/main/java/site/walkies/walkie/domain/spot/service/dto/response/SpotResponseDto.java
  src/main/java/site/walkies/walkie/global/config/H3Config.java
Labels: feat, 🟠 높음

#104 Fix/#103 : cors 설정 추가, Webmvc 설정 Security로 이동
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
Labels: fix, 🔴 긴급

#107 Fix/#106 : 리뷰 가져올 때 멤버의 닉네임도 함께 가져오도록 수정
  src/main/java/site/walkies/walkie/domain/review/service/ReviewService.java
  src/main/java/site/walkies/walkie/domain/review/service/dto/response/GetReviewResponse.java
Labels: fix, 🟠 높음

#108 Feat/#105 : Apple 로그인 기능 구현
  src/main/java/site/walkies/walkie/domain/auth/service/AppleService.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/global/auth/dto/ApplePublicKeyResponse.java
  src/main/java/site/walkies/walkie/global/auth/utils/AppleJwtValidator.java
  src/main/java/site/walkies/walkie/global/auth/utils/AppleKeyUtils.java
Labels: feat, 🟠 높음

#111 Fix/#109 : 로그인(회원가입) 로직을 체크/로그인 & 회원가입 로직으로 분리
  src/main/java/site/walkies/walkie/domain/auth/controller/AuthController.java
  src/main/java/site/walkies/walkie/domain/auth/service/AppleService.java
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/request/AuthCheckRequestDto.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/request/AuthSignupRequestDto.java
  src/main/java/site/walkies/walkie/domain/member/service/MemberLoginService.java
  src/main/java/site/walkies/walkie/domain/spot/entity/SpotPhoto.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
  src/main/java/site/walkies/walkie/global/web/exception/CustomException.java
  src/main/java/site/walkies/walkie/global/web/exception/GlobalExceptionHandler.java
Labels: fix, 🟠 높음

#112 Feat/#34 : 리프레시 토큰 기능 구현
  src/main/java/site/walkies/walkie/domain/auth/controller/AuthController.java
  src/main/java/site/walkies/walkie/domain/auth/service/AuthService.java
  src/main/java/site/walkies/walkie/domain/auth/service/dto/request/RefreshTokenRequestDto.java
  src/main/java/site/walkies/walkie/domain/member/token/MemberRefreshToken.java
  src/main/java/site/walkies/walkie/domain/member/token/MemberRefreshTokenRepository.java
  src/main/java/site/walkies/walkie/domain/member/token/MemberRefreshTokenService.java
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/auth/utils/JWTProvider.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
  src/main/java/site/walkies/walkie/global/web/exception/ErrorCode.java
Labels: feat, 🟠 높음

#114 Hotfix/#113 : Spring Security에서 OPTIONS 요청 허용하도록 변경
  src/main/java/site/walkies/walkie/global/auth/filter/JwtFilter.java
  src/main/java/site/walkies/walkie/global/config/SecurityConfig.java
Labels: fix, 🔴 긴급
